name: playlistmaster
description: Android client for playlist master.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  flutter_animator: ^3.2.2
  flutter_animate: ^4.2.0
  # just_audio: ^0.9.34
  just_audio_mpv: ^0.1.7
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  material_design_icons_flutter: ^7.0.7296
  flutter_lyric: ^2.0.4+6
  animations: ^2.0.7
  just_audio_background: ^0.0.1-beta.10
  path_provider: ^2.0.15
  fluttertoast: ^8.2.2
  flutter_cache_manager: ^3.3.0
  logger: ^1.4.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  flutter_vlc_player: ^7.2.0
  cached_video_player: ^2.0.4
  fplayer:
    git:
      url: https://github.com/loph3xertoi/fplayer.git
      ref: master
  better_player:
    git:
      url: https://github.com/loph3xertoi/betterplayer.git
      ref: master
  just_audio:
    git:
      url: https://github.com/loph3xertoi/just_audio.git
      ref: minor
      path: just_audio
  screen_brightness: ^0.2.2
  intl: ^0.18.1
  bottom_sheet: ^3.1.0
  city_picker_china: ^0.1.0
  ip_geolocation_io: ^1.0.1
  humanize_big_int: ^1.0.1
  lottie: ^2.6.0
  flutter_html: ^3.0.0-beta.2
  image_network: ^2.5.4+1
  form_builder_image_picker: ^4.0.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  cross_file: ^0.3.3+4
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  feedback: ^2.6.0
  flutter_email_sender: ^6.0.1
  url_launcher: ^6.1.14
  mailjet: ^1.0.3+3
  log_export: ^1.0.0
  archive: ^3.3.8
  mailer: ^6.0.1
  # bottom_sheet:
  #   git:
  #     url: git@github.com:loph3xertoi/flutter-bottom-sheet.git
  #     ref: SNP-304_bottom_sheet_offset
dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome.png
    - assets/images/default.jpg
    - assets/images/avatar.png
    - assets/images/home_button.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/gender_secret.png
    - assets/images/ncm_mv.png
    - assets/images/no_song.png
    - assets/images/vip_item_qqmusic.png
    - assets/images/vip_item_ncm.png
    - assets/images/song_playing_state.webp
    - assets/images/pm_round.png
    - assets/images/pm_square.png
    - assets/images/qqmusic.png
    - assets/images/netease.png
    - assets/images/bilibili.png
    - assets/images/qqmusic_vip.png
    - assets/images/qqmusic_listenlv.png
    - assets/images/china_mobile.png
    - assets/images/china_telecom.png
    - assets/images/video_buffering.json
    - assets/images/bili_resource_playing.webp
    - assets/images/phone.webp
    - assets/images/idcard.webp
    - assets/images/bili_empty.webp
    - assets/images/bili_animation.webp
    - assets/images/bili_lv0.png
    - assets/images/bili_lv1.png
    - assets/images/bili_lv2.png
    - assets/images/bili_lv3.png
    - assets/images/bili_lv4.png
    - assets/images/bili_lv5.png
    - assets/images/bili_lv6.png
    - assets/images/bili_lv7.png
    - assets/images/bili_lv7_2.png
    - assets/images/bili_lv8.png
    - assets/images/bili_lv8_2.png
    - assets/images/bili_lv9.png
    - assets/images/bili_lv9_2.png
    - assets/images/bili_thumbup.png
    - assets/images/bili_thumbup_outline.png
    - assets/images/bili_danmaku.png
    - assets/images/bili_play_count.png
    - assets/images/bili_page.png
    - assets/images/bili_loading.webp
    - assets/images/bili_favorite.png
    - assets/images/bili_favorite_outline.png
    - assets/images/bili_coin.png
    - assets/images/bili_coin_outline.png
    - assets/images/bili_share.png
    - assets/images/bili_share_outline.png
    - assets/images/lottie_wave.json
    - assets/images/up.png
    - assets/images/default_library_cover.png
    - assets/images/songs_cover/parrot.jpeg
    - assets/images/songs_cover/tit.jpeg
    - assets/images/songs_cover/tit.png
    - assets/images/songs_cover/owl.jpeg
    - assets/images/songs_cover/budgerigar.jpeg
    - assets/images/songs_cover/bluejay.jpeg
    - assets/images/songs_cover/columbidae.jpeg
    - assets/images/songs_cover/hummingbirds.jpeg
    - assets/images/songs_cover/toucans.jpeg
    - assets/images/songs_cover/finches.jpeg
    - assets/images/songs_cover/bluebirds.jpeg
    - assets/images/playlist_cover/bird.png
    - assets/images/playlist_cover/zebra.png
    - assets/images/playlist_cover/cat.png
    - assets/images/playlist_cover/owl.png
    - assets/images/playlist_cover/shark.png
    - assets/images/playlist_cover/panther.png
    - assets/images/playlist_cover/lion.png
    - assets/images/playlist_cover/fox.png
    - assets/images/playlist_cover/dog.png
    - assets/images/playlist_cover/dolphin.png
    - assets/images/playlist_cover/rabbit.png
    - assets/images/playlist_cover/elephant.png
    - assets/images/playlist_cover/wolf.png
    - assets/images/playlist_cover/dove.png
    - assets/images/playlist_cover/snake.png
    - assets/images/playlist_cover/bear.png
    - assets/images/playlist_cover/bee.png
    - assets/images/playlist_cover/panda.png
    - assets/images/playlist_cover/koala.png
    - assets/images/playlist_cover/lizard.png
    - assets/images/playlist_cover/test.jpg
    - assets/images/cloud.png
    - assets/images/cloud2.png
    - assets/images/cloud3.png
    - assets/images/moon.png
    - assets/images/mountain1.png
    - assets/images/mountain2.png
    - assets/images/mountain2_night.png
    - assets/images/mountain_night.png

    - assets/audios/parrot.mp3
    - assets/audios/tit.mp3
    - assets/audios/owl.mp3
    - assets/audios/budgerigar.mp3
    - assets/audios/bluejay.mp3
    - assets/audios/columbidae.mp3
    - assets/audios/hummingbirds.mp3
    - assets/audios/toucans.mp3
    - assets/audios/finches.mp3
    - assets/audios/bluebirds.mp3
    - assets/audios/lyrics.mp3
