name: playlistmaster
description: Android client for playlist master.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  flutter_animator: ^3.2.2
  flutter_animate: ^4.2.0
  just_audio: ^0.9.34
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  material_design_icons_flutter: ^7.0.7296
  flutter_lyric: ^2.0.4+6
  animations: ^2.0.7
  just_audio_background: ^0.0.1-beta.10
  path_provider: ^2.0.15
  dio: ^5.2.1+1
  fluttertoast: ^8.2.2
  flutter_cache_manager: ^3.3.0
  logger: ^1.4.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  flutter_vlc_player: ^7.2.0
  cached_video_player: ^2.0.4
  fplayer:
    git:
      url: https://github.com/loph3xertoi/fplayer.git
      ref: master
  screen_brightness: ^0.2.2
  intl: ^0.18.1
  bottom_sheet: ^3.1.0
  city_picker_china: ^0.1.0
  ip_geolocation_io: ^1.0.1
  # bottom_sheet:
  #   git:
  #     url: git@github.com:loph3xertoi/flutter-bottom-sheet.git
  #     ref: SNP-304_bottom_sheet_offset
dependency_overrides:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome.png
    - assets/images/default.jpg
    - assets/images/avatar.png
    - assets/images/home_button.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/gender_secret.png
    - assets/images/no_song.png
    - assets/images/vip_item_qqmusic.png
    - assets/images/vip_item_ncm.png
    - assets/images/song_playing_state.webp
    - assets/images/pm_round.png
    - assets/images/pm_square.png
    - assets/images/qqmusic.png
    - assets/images/netease.png
    - assets/images/bilibili.png
    - assets/images/qqmusic_vip.png
    - assets/images/qqmusic_listenlv.png
    - assets/images/songs_cover/parrot.jpeg
    - assets/images/songs_cover/tit.jpeg
    - assets/images/songs_cover/tit.png
    - assets/images/songs_cover/owl.jpeg
    - assets/images/songs_cover/budgerigar.jpeg
    - assets/images/songs_cover/bluejay.jpeg
    - assets/images/songs_cover/columbidae.jpeg
    - assets/images/songs_cover/hummingbirds.jpeg
    - assets/images/songs_cover/toucans.jpeg
    - assets/images/songs_cover/finches.jpeg
    - assets/images/songs_cover/bluebirds.jpeg
    - assets/images/playlist_cover/bird.png
    - assets/images/playlist_cover/zebra.png
    - assets/images/playlist_cover/cat.png
    - assets/images/playlist_cover/owl.png
    - assets/images/playlist_cover/shark.png
    - assets/images/playlist_cover/panther.png
    - assets/images/playlist_cover/lion.png
    - assets/images/playlist_cover/fox.png
    - assets/images/playlist_cover/dog.png
    - assets/images/playlist_cover/dolphin.png
    - assets/images/playlist_cover/rabbit.png
    - assets/images/playlist_cover/elephant.png
    - assets/images/playlist_cover/wolf.png
    - assets/images/playlist_cover/dove.png
    - assets/images/playlist_cover/snake.png
    - assets/images/playlist_cover/bear.png
    - assets/images/playlist_cover/bee.png
    - assets/images/playlist_cover/panda.png
    - assets/images/playlist_cover/koala.png
    - assets/images/playlist_cover/lizard.png
    - assets/images/playlist_cover/test.jpg
    - assets/images/cloud.png
    - assets/images/cloud2.png
    - assets/images/cloud3.png
    - assets/images/moon.png
    - assets/images/mountain1.png
    - assets/images/mountain2.png
    - assets/images/mountain2_night.png
    - assets/images/mountain_night.png

    - assets/audios/parrot.mp3
    - assets/audios/tit.mp3
    - assets/audios/owl.mp3
    - assets/audios/budgerigar.mp3
    - assets/audios/bluejay.mp3
    - assets/audios/columbidae.mp3
    - assets/audios/hummingbirds.mp3
    - assets/audios/toucans.mp3
    - assets/audios/finches.mp3
    - assets/audios/bluebirds.mp3
    - assets/audios/lyrics.mp3
